### ISSUE TITLE
[SUGGEST]: this project did not have any chart of workflow?

### ISSUE THREAD

**Issue by mikoloism** [sisrsis/STM32_MODBUS_lib#3]
I'm want to help to contribute this project. but i can't do anything. project not have structure and i can not know how am i can add files and write functions. exactly, i don't know what should am i write?
Maybe we need To-Do list in TODO.md file?

**Comment by mikoloism** [comment]
# To-Do

make a list of todo's should be in projects.
example:

- [ ] implement modbus Remote Terminal Unit (or RTU) mechanisms
- [ ] write document for them
- [ ] and so on
